{% set name = "pybtex" %}
{% set version = "0.22.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "bc6aaf8c5b56c9c5cfe34fd4171295c2b637193d2265b02c10db5608aec11aba" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 1000
  entry_points:
    - pybtex = pybtex.__main__:main
    - pybtex-convert = pybtex.database.convert.__main__:main
    - pybtex-format = pybtex.database.format.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - pyyaml >=3.01
    - latexcodec >=1.0.4
    - six
  run:
    - python
    - setuptools
    - pyyaml >=3.01
    - latexcodec >=1.0.4
    - six

test:
  imports:
    - pybtex
    - pybtex.backends
    - pybtex.bibtex
    - pybtex.charwidths
    - pybtex.database
    - pybtex.database.convert
    - pybtex.database.format
    - pybtex.database.input
    - pybtex.database.output
    - pybtex.markup
    - pybtex.plugin
    - pybtex.style
    - pybtex.style.formatting
    - pybtex.style.labels
    - pybtex.style.names
    - pybtex.style.sorting
  commands:
    - pybtex --help
    - pybtex-convert --help
    - pybtex-format --help

about:
  home: https://pybtex.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A BibTeX-compatible bibliography processor in Python
  description: Pybtex reads citation information from a file and produces a formatted
               bibliography. BibTeX style files are supported. Alternatively it is possible
               to write styles in Python.
  doc_url: http://pythonhosted.org/pybtex/
  dev_url: https://bitbucket.org/pybtex-devs/pybtex/

extra:
  recipe-maintainers:
    - croth1
