{% set name = "pybtex" %}
{% set version = "0.25.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybtex-{{ version }}.tar.gz
  sha256: 10684ffb05af33b041b06dabe15868078fd75847b24e1dffd8dd91348bbb3a4b

build:
  number: 0
  noarch: python
  entry_points:
    - pybtex = pybtex.__main__:main
    - pybtex-convert = pybtex.database.convert.__main__:main
    - pybtex-format = pybtex.database.format.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - pyyaml >=3.01
    - latexcodec >=1.0.4
    - importlib-metadata

test:
  imports:
    - pybtex
    - pybtex.backends
    - pybtex.bibtex
    - pybtex.charwidths
    - pybtex.database
    - pybtex.database.convert
    - pybtex.database.format
    - pybtex.database.input
    - pybtex.database.output
    - pybtex.markup
    - pybtex.plugin
    - pybtex.style
    - pybtex.style.formatting
    - pybtex.style.labels
    - pybtex.style.names
    - pybtex.style.sorting
  commands:
    - pip check
    - pybtex --help
    - pybtex-convert --help
    - pybtex-format --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pybtex.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A BibTeX-compatible bibliography processor in Python
  description: Pybtex reads citation information from a file and produces a formatted bibliography. BibTeX style files are supported. Alternatively it is possible to write styles in Python.
  doc_url: http://pythonhosted.org/pybtex/
  dev_url: https://bitbucket.org/pybtex-devs/pybtex/

extra:
  recipe-maintainers:
    - croth1
    - ocefpaf
